### ISSUE TITLE
Add log level to config

### ISSUE THREAD

**Issue by kelunik** [coolcrowd/object-service#110]
Log level for Log4j

**Comment by LeanderK** [comment]
how its normally done is that you provide a custom config file an pass it via `-Dlog4j.configurationFile=location`.

**Comment by kelunik** [comment]
Configuration should be at one single place, not spread over multiple files.

**Comment by LeanderK** [comment]
that depends on the software, log4j expects a special file (but there are also ways to configure it per code, but thats pretty ugly as i have experienced first hand).

**Comment by kelunik** [comment]
I will add a proposal.
