### ISSUE TITLE
MoneyTransferManager should expect MailInterface instead of MailHandler implementation

### ISSUE THREAD

**Issue by simonkorz** [coolcrowd/object-service#152]
[MoneyTransferManager](https://github.com/coolcrowd/object-service/blob/master/src/main/java/edu/kit/ipd/crowdcontrol/objectservice/moneytransfer/MoneyTransferManager.java#L51) constructor should take the Interfaces  `mailSender` and  `mailFetcher` instead of the implementation `mailHandler`.

**Comment by marcelhollerbach** [comment]
also you could move the config of the mail into yaml, its currently a real pain to config mutliple files, since there is currently no sample file.
We should also have a way to debug, so we dont need the mailconfig on dev systems (see pr command mail line)

**Comment by kelunik** [comment]
For development, we should have a dummy handler that just prints the sent messages using the logger.

**Comment by marcelhollerbach** [comment]
yeah, take a look at the pr.

**Comment by kelunik** [comment]
For reference: https://github.com/coolcrowd/object-service/pull/148

**Comment by marcelhollerbach** [comment]
well its merged ...

**Comment by kelunik** [comment]
If you write _"see pr"_, better provide a link for (later) reference.

**Comment by marcelhollerbach** [comment]
Thx captain, I think this gets the award for the uselessed comment ever :D

**Comment by TheRittler** [comment]
@kelunik, isn't the commandLineHandler the kind of dummy handler you wanted?

**Comment by TheRittler** [comment]
@marcelhollerbach We will have really awful code and many attributes in yaml, if i convert the properties to yaml, because i need support for most of these properties
https://javamail.java.net/nonav/docs/api/com/sun/mail/imap/package-summary.html

**Comment by TheRittler** [comment]
Why should i take the MailSender and MailFetcher Interface? If i do this, i also can completely separate MailSender and MailFetcher and delete the MailHandler, because the mailHandler would be nonsense then

**Comment by LeanderK** [comment]
i think you are onto something

**Comment by TheRittler** [comment]
So the Solution is splitting up MailHandler? Or what do you want to say? ;)

**Comment by kelunik** [comment]
It's an implementation detail that they're combined currently. They can be split up, but don't have to. The dependency requirements in the constructor should be separated into the interfaces either way.

**Comment by TheRittler** [comment]
#156

**Comment by marcelhollerbach** [comment]
no, keep the issue open as long as the pr exists.
