### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/object-service#163]
what are the modules that need extensive documentation?
Who is responsible for what?

**Comment by simonkorz** [comment]
I need to write documentation on how to set up and configure pybossa #164

**Comment by kelunik** [comment]
- [x] Setup
- [x] Authentication
- [x] Pybossa

**Comment by LeanderK** [comment]
- [x] DB-doku

**Comment by TheRittler** [comment]
- [x] Mail
