### ISSUE TITLE
Failed State

### ISSUE THREAD

**Issue by kelunik** [coolcrowd/object-service#171]
Discuss, how publish fails should be handled. @LeanderK @lucaskrauss @marcelhollerbach

**Comment by marcelhollerbach** [comment]
In stopgap ? in normal start ? Have you looked what is currently happening?

**Comment by kelunik** [comment]
@LeanderK Raised this concern during the meeting, I just created the issue.

**Comment by LeanderK** [comment]
in normal start, all failed platform get unpublished, but we can't communicate that to the control-ui, since there we only have global state and not platform-specific state

**Comment by LeanderK** [comment]
currently all failed platform have the status publishing_failed in the db

**Comment by marcelhollerbach** [comment]
well, _all_ platforms gets unpublished. So the user can click a second time on the Publish button, not sure if the publishing_failed is the right way to go.

**Comment by LeanderK** [comment]
hmm i don't think that all platforms get unpublished. This may be the more sensible way to go. But i think publishing_failed is right, maybe add another state to the protos so that the control-ui can try to publish again?

**Comment by marcelhollerbach** [comment]
the current way which is done (expected someone changed it) is that all platforms get unpublished since we have to keep the consistence for the states...

**Comment by LeanderK** [comment]
no, i am pretty sure its not, since publishTask() is called once per platform

**Comment by marcelhollerbach** [comment]
yeah thats the way the platformManager deals with it, but take a look at startExperiment

**Comment by LeanderK** [comment]
ok, it is handled outside the platformManager

**Comment by marcelhollerbach** [comment]
and I am also not sure if it is good if we are introducing a new state, since we have to define how it works, (can you add and remove platforms while in this mode ?). 
@phimonk what do you think on "spamming" pypossa for that purpose.

**Comment by LeanderK** [comment]
the state is there since weeks ;)

**Comment by marcelhollerbach** [comment]
I thought we are talking about the proto state? ;)

**Comment by LeanderK** [comment]
i was talking about the database :D There is not much definition need for failed state i think and it would increase usability

**Comment by marcelhollerbach** [comment]
@lucaskrauss @kelunik  w0rk w0rk w0rk

A platform on a experiment can have a state Successfull/Failed.

A Failed platform can be removed even if the experiment is running.
A Failed platform should be able to be started individual.
Once a Failed platform is published successfully its not Failed anymore (HA!)

Opinions ?

**Comment by kelunik** [comment]
Too much work, we have just one week to go.

**Comment by LeanderK** [comment]
ok, as an workaround I can translate the failed state into draft, and we can mark this as an enhancement

**Comment by LeanderK** [comment]
but the os side is not that much work, since the db already supports these, maybe when i have some time ;)

**Comment by kelunik** [comment]
Question is how to display it in any client like the `control-ui`.

**Comment by marcelhollerbach** [comment]
So what are we doing ?

**Comment by LeanderK** [comment]
i would like to add the Failed state to the proto and display a red warning that reads "an error occurred while trying to publish the experiment xy".

**Comment by LeanderK** [comment]
Every time we fail to publish somebody should look up what was going wrong, since there could be a  Mturk hit floating around that we don't know about.

**Comment by marcelhollerbach** [comment]
As said above this can never happen since _ALL_ Platforms are unpublished if one failed.

**Comment by LeanderK** [comment]
there was still an error...maybe we didn't get a key, idk. I still think that it should be exposed to the user, since right now we are relying solely on the recovery mechanism.

**Comment by marcelhollerbach** [comment]
The call to patch the state will then end in 500 with a exception (and I guess there will be the name of the platform which wasnt doing it correctly and I guess the exception from the platform). For NOW it works, thats my point, but the way with the single platform displayed with an error is quite better.

**Comment by kelunik** [comment]
There's still an error displayed to the user if publishing fails.

**Comment by marcelhollerbach** [comment]
you dont do that?

**Comment by kelunik** [comment]
If it fails with an error, I display the provided message. If it succeeds, but the state didn't change, I still display an error, but (obviously) can't tell the user why.

**Comment by TheRittler** [comment]
Did this get solved anywhere?

**Comment by marcelhollerbach** [comment]
No.

**Comment by kelunik** [comment]
"Solved" via `INVALID`?

**Comment by LeanderK** [comment]
i think it is kinda solved, i would still let this be open because there is room for improvement
