### ISSUE TITLE
Who is using which email adress

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/object-service#180]
Can all people tell which email adresses they are using? We should split this in the config and clarify
@LeanderK @kelunik @phimonk @redalertexpert @lucaskrauss

**Comment by kelunik** [comment]
Everyone uses the same mail handler. https://github.com/coolcrowd/object-service/blob/master/src/main/java/edu/kit/ipd/crowdcontrol/objectservice/Main.java#L202

**Comment by marcelhollerbach** [comment]
dont know if this is a good idea ...

**Comment by marcelhollerbach** [comment]
maybe add a config class Mail with addr. pw servers which can be applyed to notifications newsletter and payment, if someone want one adress he can use yaml to only specify it once.

**Comment by kelunik** [comment]
I think it's fine that all use the same address for sending messages. Usually, that'd be something like `noreply@example.com`.

**Comment by marcelhollerbach** [comment]
no, different services should use different mailadresses, an payment is in generel something else than notifications.

**Comment by TheRittler** [comment]
I cant see a problem in using the same mail address, but if you want so i would prefer a Mail config class with different attributes for each usage of Mail: e.g. notificationMailAddress, notificationMailUsername, notificationMailPassword, moneytransferMailAddress, moneytransferMailUsername, moneytransferMailPassword and so on

**Comment by marcelhollerbach** [comment]
well why not having a class with String address, password and a class with "Mail moneyTransfer, Notification"? Maybe we should also make it possible to specify which mailbackend to use in the config.

**Comment by TheRittler** [comment]
I don't understand your suggestion. 
And I can't think of an use case, where you need the mails get sent and received by different mailservers.

**Comment by marcelhollerbach** [comment]
ehm why should we have such a usecase ? 
What I am talking about is more of doing something like 

```
class Mail {
   String user
   String password
   String server
}
```

and 

```
class Main {
   ...
   Mail moneytransfer, notifications;
   ...
}
```

So you can do something like 

```
&mailconfig:
   user: foo
   password: bar
   server: example.com

main.moneytransfer: *mailconfig
main.notification: *mailconfig
```

in yaml,

**Comment by LeanderK** [comment]
i don't use any

**Comment by TheRittler** [comment]
@marcelhollerbach or what means "we should make it possible to specify which mailbackend to use in the config"? And i dont understand your splitting in user password and server. Why not username, password and mailaddress? The username gets used to authenticate with the server. And e.g. at gmail the username is the full mail addres. At web.de the username is just the prefix of the mail address.

**Comment by marcelhollerbach** [comment]
mailbackend at our end is something like messageBackend, maybe someone wants to see payments in the cli but notifications not (debug reasons). Maybe we are adding one day a telegram backend and this should be used for notifications. This was just open thinking. 

Yeah we need username password mailadress and server.
