### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by TheRittler** [coolcrowd/object-service#210]
The MailHandlerTest doesn't compile, it calls a method Main.getConfig() which doesn't exist (anymore).

**Comment by LeanderK** [comment]
well this can't be possible , travis can compile

**Comment by marcelhollerbach** [comment]
Its fixed with The latested pr

**Comment by TheRittler** [comment]
It can be, Travis doesn't compile integration test code. But good, if it is fixed

**Comment by LeanderK** [comment]
ah, i overlooked the Test part, yeah that can be
