### ISSUE TITLE
Duplicates get presented in rating-view 

### ISSUE THREAD

**Issue by lckr** [coolcrowd/object-service#274]
- Ratings can change the quality of duplicate-answers

The main problem is that we lack internal identification of duplicates.
Introducing a duplicate-flag can solve this issue

EDIT: deleted parts belonging to the worker-service

**Comment by LeanderK** [comment]
moved parts to correct location coolcrowd/worker-service#43

**Comment by marcelhollerbach** [comment]
noep.

**Comment by lckr** [comment]
NoepNoep
