### ISSUE TITLE
MoneyTransfer is not working

### ISSUE THREAD

**Issue by TheRittler** [coolcrowd/object-service#312]
moneytransfer logs stop after  fetching new mails from the server. Further testing brought me, that everything works fine until adding giftcodes to the db. Nothing happens after addGiftCode(). (I guess the addGiftCode()-method never completes, so this seems to be a db issue)

**Comment by LeanderK** [comment]
i really don't think this is an db-iussue

**Comment by LeanderK** [comment]
can you provide steps to reproduce it?

**Comment by kelunik** [comment]
@redalertexpert Just add a test in `rest-test`, we have to rename that anyway. Add a test that shows it failing.

**Comment by TheRittler** [comment]
#316 added a test, so what to do now?

**Comment by LeanderK** [comment]
well...the test is not failing

**Comment by TheRittler** [comment]
? The test is failing.
It's in integration tests, travis doesn't execute integration tests. That's why i put it in rest-tests before

**Comment by LeanderK** [comment]
ah ok, sry my fault ;)
